Repository hwiwonK/MacC-Team-Maddori.Apple-Server, pull requests merged in 2022-12, with the labels that each got.

#90 [FEAT] Release/v1.2 배포 완료
  Maddori.Apple-Server/.idea/.gitignore
  Maddori.Apple-Server/app.js
  Maddori.Apple-Server/bin/www
  Maddori.Apple-Server/config/config.js
  Maddori.Apple-Server/middlewares/auth.js
  Maddori.Apple-Server/middlewares/validate.js
  Maddori.Apple-Server/models/feedback.js
  Maddori.Apple-Server/models/index.js
  Maddori.Apple-Server/models/reflection.js
  Maddori.Apple-Server/models/team.js
  Maddori.Apple-Server/models/user.js
  Maddori.Apple-Server/models/userteam.js
  Maddori.Apple-Server/models/usertoken.js
  Maddori.Apple-Server/package-lock.json
  Maddori.Apple-Server/package.json
  Maddori.Apple-Server/routes/auth/auth.js
  Maddori.Apple-Server/routes/auth/index.js
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/feedbacks/index.js
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/reflections/reflections.js
  Maddori.Apple-Server/routes/teams/index.js
  Maddori.Apple-Server/routes/teams/teams.js
  Maddori.Apple-Server/routes/users/index.js
  Maddori.Apple-Server/routes/users/users.js
  Maddori.Apple-Server/seeders/testData.js
  Maddori.Apple-Server/utils/jwt.util.js
Labels: 🌏 Deploy

#91 [FEAT] release/v1.2 배포 완료
  Maddori.Apple-Server/models/feedback.js
Labels: 🌏 Deploy

#93 [FEAT] 피드백 포맷 수정
  Maddori.Apple-Server/middlewares/validate.js
  Maddori.Apple-Server/models/feedback.js
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/seeders/testData.js
Labels: ✨ Feature

#98 [FEAT] reflection 일정 현재(분 단위)로 등록할 수 있도록 수정
  Maddori.Apple-Server/middlewares/auth.js
  Maddori.Apple-Server/routes/reflections/reflections.js
Labels: ✨ Feature

#100 [FEAT] feedback content의 글자 수 제한 수정
  Maddori.Apple-Server/middlewares/validate.js
  Maddori.Apple-Server/models/feedback.js
Labels: ✨ Feature

#96 [CHORE] API URI 변경
  Maddori.Apple-Server/app.js
  Maddori.Apple-Server/routes/auth/index.js
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/users/index.js
Labels: 🛠 Chore, 📡 API
