Repository hwiwonK/MacC-Team-Maddori.Apple-Server, pull requests merged in 2022-11, with the labels that each got.

#12 [FEAT] 더미 데이터(seed) 추가
  Maddori.Apple-Server/models/reflection.js
  Maddori.Apple-Server/models/team.js
  Maddori.Apple-Server/seeders/testData.js
Labels: ✨ Feature

#16 [FEAT] Setup 페이지 api 구현 - 유저 등록, 팀 합류, 팀 탈퇴, 팀 등록
  Maddori.Apple-Server/app.js
  Maddori.Apple-Server/models/reflection.js
  Maddori.Apple-Server/routes/feedbacks/index.js
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/teams/index.js
  Maddori.Apple-Server/routes/teams/teams.js
  Maddori.Apple-Server/routes/users/index.js
  Maddori.Apple-Server/routes/users/users.js
Labels: ✨ Feature

#20 [FEAT] Home View api 구현 - 팀 정보, 현재 회고 정보
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/reflections/reflections.js
  Maddori.Apple-Server/routes/teams/index.js
  Maddori.Apple-Server/routes/teams/teams.js
Labels: ✨ Feature

#24 [FEAT] AddFeedback View api 구현 - 팀 멤버 정보, 피드백 추가
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/feedbacks/index.js
  Maddori.Apple-Server/routes/teams/index.js
  Maddori.Apple-Server/routes/teams/teams.js
Labels: ✨ Feature, 📡 API

#26 [CHORE] 에러 발생 http status code 400으로 변경
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/reflections/reflections.js
  Maddori.Apple-Server/routes/teams/teams.js
  Maddori.Apple-Server/routes/users/users.js
Labels: 🛠 Chore

#28 [CHORE] feedback 테이블 is_favorite 필드 삭제
  Maddori.Apple-Server/models/feedback.js
Labels: 🛠 Chore, 📁 Database

#31 [CHORE] response 포맷 수정 및 code convention 맞추기
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/reflections/reflections.js
  Maddori.Apple-Server/routes/teams/index.js
  Maddori.Apple-Server/routes/teams/teams.js
  Maddori.Apple-Server/routes/users/users.js
Labels: 🛠 Chore

#30 [FEAT] 회고 목록 조회, 특정 타입 피드백 조회 api 구현
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/feedbacks/index.js
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/reflections/reflections.js
Labels: ✨ Feature, 📡 API

#34 [FEAT] Home View api 구현 - 회고 상세 정보 추가
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/reflections/reflections.js
Labels: ✨ Feature, 📡 API

#35 [FEAT] EditFeedbackFromMe, FeedbackFromMeDetail View - Feedback 수정, 삭제 API 구현
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/feedbacks/index.js
Labels: ✨ Feature, 📡 API

#38 [FEAT] middleware 구현 - 유저의 팀 검증, 리더 검증
  Maddori.Apple-Server/app.js
  Maddori.Apple-Server/middlewares/auth.js
  Maddori.Apple-Server/routes/feedbacks/index.js
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/teams/index.js
Labels: ✨ Feature

#40 [FEAT] MyBox View api 구현 - 특정 멤버에게 작성한 피드백 가져오기
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/feedbacks/index.js
Labels: ✨ Feature, 📡 API

#41 [FEAT] InProgress View - 피드백 정보 분류, 회고 종료 API 구현
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/feedbacks/index.js
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/reflections/reflections.js
Labels: ✨ Feature, 📡 API

#42 [FEAT] middleware 구현 - 회고의 상태 검증
  Maddori.Apple-Server/app.js
  Maddori.Apple-Server/bin/www
  Maddori.Apple-Server/config/config.js
  Maddori.Apple-Server/middlewares/auth.js
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/feedbacks/index.js
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/reflections/reflections.js
  Maddori.Apple-Server/routes/teams/teams.js
  Maddori.Apple-Server/routes/users/index.js
  Maddori.Apple-Server/routes/users/users.js
Labels: ✨ Feature

#45 [BUG] response 형식 오류 수정
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/reflections/reflections.js
  Maddori.Apple-Server/routes/teams/teams.js
  Maddori.Apple-Server/routes/users/users.js
Labels: 🐞 Bugfix

#47 [BUG] getTeamAndUserFeedback, getCertainTypeFeedbackAll api 버그 수정
  Maddori.Apple-Server/config/config.js
  Maddori.Apple-Server/models/feedback.js
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
Labels: 🐞 Bugfix

#49 [CHORE] datail을 detail로 오타 수정(#48)
  Maddori.Apple-Server/routes/users/users.js
Labels: 🛠 Chore

#52 [CHORE] getCertainTeamDetail admin boolean으로 반환하도록 수정(#48)
  Maddori.Apple-Server/routes/teams/teams.js
Labels: 🛠 Chore

#54 [FEAT] user join team api 분리
  Maddori.Apple-Server/routes/teams/index.js
  Maddori.Apple-Server/routes/teams/teams.js
  Maddori.Apple-Server/routes/users/index.js
  Maddori.Apple-Server/routes/users/users.js
Labels: ✨ Feature, 📡 API

#58 [BugFix] : getPastReflectionList API 수정
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/reflections/reflections.js
Labels: 📡 API, 🐞 Bugfix

#56 [CHORE] 회고 종료 API 미들웨어 추가
  Maddori.Apple-Server/routes/reflections/index.js
Labels: 🐞 Bugfix

#60 [BUG] updateFeedback api 버그 해결
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
Labels: 🐞 Bugfix

#61 [CHORE] getCertainTypeFeedbackAll 의 response data에 feedback id 추가
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
Labels: 🛠 Chore

#66 [FIX] timezone 설정 추가하여 회고 시간 검증 에러 해결
  Maddori.Apple-Server/config/config.js
Labels: 🐞 Bugfix

#64 [BugFix] : Feedback 관련 API 수정
  Maddori.Apple-Server/.idea/.gitignore
  Maddori.Apple-Server/middlewares/auth.js
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/feedbacks/index.js
Labels: 🛠 Chore, 📡 API, 🐞 Bugfix

#71 [BUG] 회고 상태 검증 미들웨어 오류 해결 및 미들웨어 적용 사항 수정
  Maddori.Apple-Server/middlewares/auth.js
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/feedbacks/index.js
Labels: 🐞 Bugfix

#65 [FEAT] apple login 구현
  Maddori.Apple-Server/app.js
  Maddori.Apple-Server/middlewares/auth.js
  Maddori.Apple-Server/models/user.js
  Maddori.Apple-Server/models/usertoken.js
  Maddori.Apple-Server/package-lock.json
  Maddori.Apple-Server/package.json
  Maddori.Apple-Server/routes/auth/auth.js
  Maddori.Apple-Server/routes/auth/index.js
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/feedbacks/index.js
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/reflections/reflections.js
  Maddori.Apple-Server/routes/teams/index.js
  Maddori.Apple-Server/routes/teams/teams.js
  Maddori.Apple-Server/routes/users/index.js
  Maddori.Apple-Server/routes/users/users.js
  Maddori.Apple-Server/seeders/testData.js
  Maddori.Apple-Server/utils/jwt.util.js
Labels: ✨ Feature, 📡 API

#75 [CHORE] getTeamMembers response 형식 수정
  Maddori.Apple-Server/routes/teams/teams.js
Labels: 🛠 Chore

#73 [BugFix] 사용자 입력 제한
  Maddori.Apple-Server/middlewares/validate.js
  Maddori.Apple-Server/package-lock.json
  Maddori.Apple-Server/package.json
  Maddori.Apple-Server/routes/auth/auth.js
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/feedbacks/index.js
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/reflections/reflections.js
  Maddori.Apple-Server/routes/teams/index.js
  Maddori.Apple-Server/routes/teams/teams.js
  Maddori.Apple-Server/routes/users/index.js
  Maddori.Apple-Server/routes/users/users.js
Labels: 🛠 Chore, 📡 API, 🐞 Bugfix

#76 [FIX] sequelize config 에러 해결
  Maddori.Apple-Server/config/config.js
Labels: 🐞 Bugfix

#77 [BUG] feedback 추가 에러 수정
  Maddori.Apple-Server/middlewares/validate.js
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
Labels: 🐞 Bugfix

#79 [FIX] reflectionStateCheck 배열 인자 받아서 실행하도록 수정
  Maddori.Apple-Server/middlewares/auth.js
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
  Maddori.Apple-Server/routes/feedbacks/index.js
Labels: 🐞 Bugfix

#81 [ADD] getCurrentReflectionDetail 키워드 리스트 역순 설정 추가(#48)
  Maddori.Apple-Server/routes/reflections/reflections.js
Labels: 🛠 Chore

#83 [FIX] endInProgressReflection에서 recent_reflection_id 업데이트
  Maddori.Apple-Server/routes/reflections/index.js
  Maddori.Apple-Server/routes/reflections/reflections.js
Labels: 🐞 Bugfix

#84 [CHORE] response 형식 수정
  Maddori.Apple-Server/routes/feedbacks/feedbacks.js
Labels: 🛠 Chore

#85 [CHORE] appleLogin 응답 형식 수정(user_id 반환 추가)
  Maddori.Apple-Server/routes/auth/auth.js
Labels: 🛠 Chore

#88 [FEAT] 회원 탈퇴 api 구현
  Maddori.Apple-Server/routes/auth/auth.js
  Maddori.Apple-Server/routes/auth/index.js
Labels: ✨ Feature, 📡 API
